- name: Run Frontend container
  docker_container:
    name: front
    image: "dagnogo28/tp-devops-front:latest"
    pull: true
    recreate: true
    force_kill: true
    state: started
    restart_policy: always
    networks:
      - name: app_network