- name: Run Frontend container
  docker_container:
    name: frontend
    image: "dagnogo28/tp-devops-front:latest"
    state: started
    restart_policy: always
    networks:
      - name: app_network