
---
- name: Load environment variables
  include_vars:
    file: "{{ playbook_dir }}/../.env.yml"
    name: env_vars
    
# tasks file for roles/proxy
- name: Run HTTP proxy container
  docker_container:
    name: httpd
    image: dagnogo28/tp-devops-httpd:latest
    pull: true
    recreate: true
    force_kill: true
    state: started
    ports:
      - "{{ env_vars.PROXY_PORT }}:80"
    networks:
      - name: app_network