name: CI devops 2025
 
on:
  push:
    branches:
      - main
      - develop
  pull_request:
 
jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
 
      - name: Build and test with Maven
        working-directory: simple-api
        run: mvn clean verify 
     
      - name: Sonar Cloud integration
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=EmmanuelDagnogo_tp-devops-correction-docker -Dsonar.organization=tp-dev  -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml
 
 
  build-and-push-docker-image:
    needs: test-backend 
    runs-on: ubuntu-24.04
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
 
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}
 
      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./database
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}
 
      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}  

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-front:latest
          push: ${{ github.ref == 'refs/heads/main' }}
          
  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add SSH host key to known_hosts
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H emmanuel.dagnogo.takima.cloud >> ~/.ssh/known_hosts
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible playbook
        run: ansible-playbook -i ./ansible/inventories/setup.yml ./ansible/playbook.yml
      
  